export const DEPARTMENTS = [
    { label: 'Aeronautical Engineering', value: 'Aeronautical Engineering' },
    { label: 'Agricultural Engineering', value: 'Agricultural Engineering' },
    { label: 'Automobile Engineering', value: 'Automobile Engineering' },
    { label: 'Biomedical Engineering', value: 'Biomedical Engineering' },
    { label: 'Biotechnology', value: 'Biotechnology' },
    { label: 'Civil Engineering', value: 'Civil Engineering' },
    { label: 'Chemical Engineering', value: 'Chemical Engineering' },
    { label: 'Computer Science and Engineering', value: 'Computer Science and Engineering' },
    { label: 'Computer Science and Business Systems', value: 'Computer Science and Business Systems' },
    { label: 'Computer Technology', value: 'Computer Technology' },
    { label: 'Electrical and Electronics Engineering', value: 'Electrical and Electronics Engineering' },
    { label: 'Electronics and Communication Engineering', value: 'Electronics and Communication Engineering' },
    { label: 'Electronics and Instrumentation Engineering', value: 'Electronics and Instrumentation Engineering' },
    { label: 'Fashion Technology', value: 'Fashion Technology' },
    { label: 'Food Technology', value: 'Food Technology' },
    { label: 'Information Technology', value: 'Information Technology' },
    { label: 'Mechatronics Engineering', value: 'Mechatronics Engineering' },
    { label: 'Mechanical Engineering', value: 'Mechanical Engineering' },
    { label: 'Textile Technology', value: 'Textile Technology' },
    { label: 'Artificial Intelligence and Data Science', value: 'Artificial Intelligence and Data Science' },
    { label: 'Artificial Intelligence and Machine Learning', value: 'Artificial Intelligence and Machine Learning' },
    { label: 'Cyber Security', value: 'Cyber Security' }
];
